services:
  sso-postgres:
    build:
      dockerfile: Dockerfile-db
    image: sso-postgres
    container_name: sso-postgres
    ports:
      - "9898:5432"

  sso-app:
    build:
      dockerfile: Dockerfile
    image: sso-app
    container_name: sso-app
    ports:
      - "9999:9999"
    command:
      - "--spring.profiles.active=prod,noop,ssl"
    environment:
      - SSO_BASENAME=sso
      - SSO_BASEURL=sso-postgres:5432
      - SSO_BASEUSER=sso
      - SSO_BASEPASSWORD=sso
    depends_on:
      - sso-postgres